### ISSUE TITLE
[Kabuto Ver][Update 1.1] Random encounter bugged

### ISSUE THREAD

**Issue by MigasToulouse** [Omnija/Medarot-9-3ds-Translations#1]
There are 2 medabots that are bugged and cannot be captured. 

 * RaidGavial: Found in front of the waterfall and alongside the river in the area of the mist forest.
 * ChromeTortoise: Found in the watermill area in the mist forest.

When you encounter them it shows no model. During the fight they use their different parts, but you can only target them as if they were a single target. After the battle, the reward screen is never shown. 

I tried playing the **base game patched** WITHOUT the 1.1 update and I could get those medabots, no problems with the models whatsoever. It is when I install the update, when problems happen again.

Also, after installing the update AFTER capturing them, I noticed there is a typo with their names, not sure if it is related to not having enough character blanks.

Some screenshots:

 * RaidGavial:

![RaidGavial_Encounter](https://user-images.githubusercontent.com/59051756/198302449-6df41483-1be3-4609-a675-3aa22c32f92e.jpeg)
![RaidGavial_LeaderSelection](https://user-images.githubusercontent.com/59051756/198302453-36ac8797-9674-4d5f-95f5-b00d539e3ca1.jpeg)
![RaidGavial_TargetSelection1](https://user-images.githubusercontent.com/59051756/198302455-d1e077e3-92c9-48de-9aab-8b08265d3725.jpeg)
![RaidGavial_TargetSelection2](https://user-images.githubusercontent.com/59051756/198302457-f6c4c2a0-00df-427d-bf5f-1f1db242221d.jpeg)
![RaidGavial_Library_Top](https://user-images.githubusercontent.com/59051756/198303076-ed4c1065-1e7c-4808-9331-de99f9e6e94b.jpeg)
![RaidGavial_Library_Bot](https://user-images.githubusercontent.com/59051756/198303091-1a9063cc-0aa7-4886-952b-7e0cf70f32f1.jpeg)

 * ChromeTortoise:

![ChromeTortoise_Encounter](https://user-images.githubusercontent.com/59051756/198302658-9f8adcd4-ed9d-48bc-8a52-171b910e0b8a.jpeg)
![ChromeTortoise_LeaderSelection](https://user-images.githubusercontent.com/59051756/198302666-8cd1dc25-ae84-426c-9abd-70da114d752c.jpeg)
![ChromeTortoise_TargetSelection1](https://user-images.githubusercontent.com/59051756/198302669-03cd4384-13af-4407-84f0-93c2f57df5db.jpeg)
![ChromeTortoise_TargetSelection2](https://user-images.githubusercontent.com/59051756/198302671-31caf7b7-2a69-43af-8f31-0dfb6c3e641f.jpeg)
![ChromeTortoise_Library_Top](https://user-images.githubusercontent.com/59051756/198303132-bf282680-1aab-4739-9c60-f8b9a0cf1a10.jpeg)
![ChromeTortoise_Library_Bot](https://user-images.githubusercontent.com/59051756/198303145-071861e2-4f45-493a-8697-061c2f84e7b1.jpeg)

**Comment by Omnija** [comment]
We will look into it when we can. It would be appreciated if you could upload your save file as well at the location where it happens.

**Comment by MigasToulouse** [comment]
RaidGavial: Found in front of the waterfall and alongside the river in the area of the mist forest.
ChromeTortoise: Found in the watermill area in the mist forest.

Loading the save data will place you in the watermill area, so you can find the ChromeTortoise right away. The RaidGavial can be found in the waterfall. Go from the menu to River and then up one screen. That is the waterfall (in front of it).

This saved data is taken with Checkpoint.
[Debug.zip](https://github.com/Omnija/Medarot-9-3ds-Translations/files/9912893/Debug.zip)

**Comment by Omnija** [comment]
Give the latest git commit a try and see if the problem persists.

**Comment by MigasToulouse** [comment]
Solved! Thank you.
